FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
WORKDIR /src
COPY CyberSpaceNIS2.API/CyberSpaceNIS2.API.csproj CyberSpaceNIS2.API/
RUN dotnet restore CyberSpaceNIS2.API/CyberSpaceNIS2.API.csproj
COPY . .
WORKDIR /src/CyberSpaceNIS2.API
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_ENVIRONMENT=Production
ENTRYPOINT ["dotnet", "CyberSpaceNIS2.API.dll"]